### ISSUE TITLE
margem do menu

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tema-npds#1]
Em monitores menores (1366) o menu está perdendo uma margem lateral e colando na borda da tela.

veja diferença entre tela com o tema tainacan ativo e outra com o tema npds

![captura de tela de 2018-08-17 17-54-50](https://user-images.githubusercontent.com/971483/44288448-c7e6c400-a246-11e8-9e20-f3f6714d536b.png)

![captura de tela de 2018-08-17 17-54-14](https://user-images.githubusercontent.com/971483/44288453-cc12e180-a246-11e8-95b5-e0a6aa601523.png)

**Comment by alvinodigo** [comment]
Fiz o teste aqui em resoluções menores até chegar a mobile, e o menu não colou na esquerda. Esse erro ainda acontece? Você pode dar mais detalhes pra ver se é possível reproduzir o erro aqui?

Abs

**Comment by leogermani** [comment]
ta corrigido. Acho que foi a inversão das ordens dos css q o Fabiano fez
